services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: bot/Dockerfile
    depends_on:
      - redis
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
